/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cineslave.gui;

import com.cineslave.modelo.Cliente;
import com.cineslave.modelo.Empleado;
import com.cineslave.modelo.controlador.Gestor_Cliente;
import com.cineslave.modelo.controlador.Gestor_Empleado;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juanxxiii
 */
public class JPanelEmpleados extends javax.swing.JPanel {

    private JFPrincipal jfe;
    Gestor_Empleado ge;
    Connection con;

    /**
     * Creates new form JPanelEmpleados
     */
    public JPanelEmpleados(JFPrincipal _this, Connection conTotal) {
        initComponents();
        this.jfe = _this;
        this.con = conTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfDNI = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfTelefono = new javax.swing.JTextField();
        jtfFechaInicio = new javax.swing.JTextField();
        jcbCargo = new javax.swing.JComboBox<>();
        jbAlta = new javax.swing.JButton();
        jbConsulta = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("DNI");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 34, -1, -1));

        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 75, -1, -1));

        jLabel3.setText("Apellidos");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 116, -1, -1));
        add(jtfDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 121, -1));
        add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 121, -1));

        jtfApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApellidosActionPerformed(evt);
            }
        });
        add(jtfApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 124, -1));

        jLabel4.setText("Teléfono");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 34, -1, -1));

        jLabel5.setText("Fecha Inicio");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 75, -1, -1));

        jLabel6.setText("Cargo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 116, -1, -1));
        add(jtfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 31, 124, -1));
        add(jtfFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 72, 122, -1));

        jcbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Administrativo", "Taquillero", "Resto de personal" }));
        add(jcbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 113, 120, -1));

        jbAlta.setText("Alta");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });
        add(jbAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 30, 75, -1));

        jbConsulta.setText("Consulta");
        jbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaActionPerformed(evt);
            }
        });
        add(jbConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 71, -1, -1));

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });
        add(jbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 112, -1, -1));

        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });
        add(jbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 153, 75, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 187, 592, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        String dni = jtfDNI.getText();
        String nombre = jtfNombre.getText();
        String apellidos = jtfApellidos.getText();
        int telefono = Integer.parseInt(jtfTelefono.getText());
        String fechaInicio = jtfFechaInicio.getText();
        String cargo = jcbCargo.getName();
        Empleado nuevoEmpleado = new Empleado(dni, nombre, apellidos, telefono, fechaInicio, cargo);
        try {
            ge = new Gestor_Empleado(con);
            ge.altaEmpleado(nuevoEmpleado);
            JOptionPane.showMessageDialog(null, "Empleado creado");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error SQL");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error BBDD");
        }
        borrarCampos();
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaActionPerformed
        Empleado nuevoEmpleado = null;
        String dni = jtfDNI.getText();
        try {
            ge = new Gestor_Empleado(con);
            nuevoEmpleado = ge.consultaEmpleado(dni);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error SQL");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error BBDD");
        }
        jtfDNI.setText(nuevoEmpleado.getDni());
        jtfNombre.setText(nuevoEmpleado.getNombre());
        jtfApellidos.setText(nuevoEmpleado.getApellidos());
        jtfTelefono.setText(String.valueOf(nuevoEmpleado.getTelefono()));
        jtfFechaInicio.setText(nuevoEmpleado.getFechaInicio());
        jcbCargo.setSelectedItem(nuevoEmpleado.getCargo());
    }//GEN-LAST:event_jbConsultaActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        int modificaciones;
        String dni = jtfDNI.getText();
        String nombre = jtfNombre.getText();
        String apellidos = jtfApellidos.getText();
        int telefono = Integer.parseInt(jtfTelefono.getText());
        String fechaInicio = jtfFechaInicio.getText();
        String cargo = jcbCargo.getName();
        Empleado nuevoEmpleado = new Empleado(dni, nombre, apellidos, telefono, fechaInicio, cargo);
        try {
            ge = new Gestor_Empleado(con);
            modificaciones = ge.modificarEmpleado(nuevoEmpleado);
            JOptionPane.showMessageDialog(null, "Clientes modificados" + modificaciones);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error BBDD");
        }
        borrarCampos();
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        String dni = jtfDNI.getText();
        try {
            ge = new Gestor_Empleado(con);
            ge.borrarEmpleado(dni);
            JOptionPane.showMessageDialog(null, "Empleado eliminado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error BBDD");
        }
        borrarCampos();
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jtfApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfApellidosActionPerformed

    
    
    private void borrarCampos() {
        jtfDNI.setText("");
        jtfNombre.setText("");
        jtfApellidos.setText("");
        jtfTelefono.setText("");
        jtfFechaInicio.setText("");
        jcbCargo.setName("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbConsulta;
    private javax.swing.JButton jbModificar;
    private javax.swing.JComboBox<String> jcbCargo;
    private javax.swing.JTextField jtfApellidos;
    private javax.swing.JTextField jtfDNI;
    private javax.swing.JTextField jtfFechaInicio;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables
}
