/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cineslave.gui;

import com.cineslave.modelo.Sesion;
import com.cineslave.modelo.controlador.Gestor_Sesion;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author juanxxiii
 */
public class JPanelSesion extends javax.swing.JPanel {

    private JFPrincipal jfe;
    private Connection con;
    private Gestor_Sesion gs;

    JPanelSesion(JFPrincipal aThis, Connection conTotal) {
        initComponents();
        this.jfe = aThis;
        this.con = conTotal;
    }

    /**
     * Creates new form JPanelSesion
     */
    public JPanelSesion() {
        initComponents();
        try {
            System.out.println("1");
            gs.cargarSesiones();
        } catch (SQLException ex) {
            Logger.getLogger(JPanelSesion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jsHora = new javax.swing.JSpinner();
        jbAlta = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbConsultar = new javax.swing.JButton();
        jcbSesiones = new javax.swing.JComboBox<>();

        jLabel1.setText("Hora");

        jbAlta.setText("Crear sesión");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbBaja.setText("Borrar sesión");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar sesión");

        jbConsultar.setText("Consultar sesión");

        jcbSesiones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jsHora, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAlta)
                        .addGap(131, 131, 131)
                        .addComponent(jbModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jbConsultar))
                    .addComponent(jbBaja)
                    .addComponent(jcbSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jsHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlta)
                    .addComponent(jbModificar)
                    .addComponent(jbConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jcbSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbBaja)
                .addGap(98, 98, 98))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        Sesion _nuevaSesion = new Sesion(Integer.parseInt(jsHora.getValue().toString()), true);
        try {
            gs = new Gestor_Sesion(con);
            gs.crearSesion(_nuevaSesion);
        } catch (SQLException ex) {
            Logger.getLogger(JPanelProveedor.class.getName()).log(Level.SEVERE, null, ex);
            //altaProveedor
        } catch (Exception ex) {
            Logger.getLogger(JPanelProveedor.class.getName()).log(Level.SEVERE, null, ex);
            //Gestor_proveedor(con)
        }
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        try {
            gs = new Gestor_Sesion(con);
            gs.borrarSesion(Integer.parseInt(String.valueOf(jcbSesiones.getSelectedItem())));
        } catch (SQLException ex) {
            Logger.getLogger(JPanelProveedor.class.getName()).log(Level.SEVERE, null, ex);
            //altaProveedor
        } catch (Exception ex) {
            Logger.getLogger(JPanelProveedor.class.getName()).log(Level.SEVERE, null, ex);
            //Gestor_proveedor(con)
        }
    }//GEN-LAST:event_jbBajaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JComboBox<String> jcbSesiones;
    private javax.swing.JSpinner jsHora;
    // End of variables declaration//GEN-END:variables
}
