/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cineslave.gui;

import com.cineslave.modelo.Cliente;
import com.cineslave.modelo.Empleado;
import com.cineslave.modelo.controlador.Gestor_Cliente;
import com.cineslave.modelo.controlador.Gestor_Empleado;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juanxxiii
 */
public class JPanelEmpleados extends javax.swing.JPanel {

    private JFPrincipal jfe;
    Gestor_Empleado ge;
    Connection con;

    /**
     * Creates new form JPanelEmpleados
     */
    public JPanelEmpleados(JFPrincipal _this, Connection conTotal) {
        initComponents();
        this.jfe = _this;
        this.con = conTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfDNI = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfTelefono = new javax.swing.JTextField();
        jtfFechaInicio = new javax.swing.JTextField();
        jcbCargo = new javax.swing.JComboBox<>();
        jbAlta = new javax.swing.JButton();
        jbConsulta = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("DNI");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellidos");

        jtfApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApellidosActionPerformed(evt);
            }
        });

        jLabel4.setText("Teléfono");

        jLabel5.setText("Fecha Inicio");

        jLabel6.setText("Cargo");

        jcbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Administrativo", "Taquillero", "Resto de personal" }));

        jbAlta.setText("Alta");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbConsulta.setText("Consulta");
        jbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultaActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jtfFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jbConsulta))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jtfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addComponent(jcbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jbModificar))
            .addGroup(layout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbAlta))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jtfFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jbConsulta)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(jtfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jcbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jbModificar)))
                .addGap(18, 18, 18)
                .addComponent(jbBorrar)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        String dni = jtfDNI.getText();
        String nombre = jtfNombre.getText();
        String apellidos = jtfApellidos.getText();
        int telefono = Integer.parseInt(jtfTelefono.getText());
        String fechaInicio = jtfFechaInicio.getText();
        String cargo = jcbCargo.getName();
        Empleado nuevoEmpleado = new Empleado(dni, nombre, apellidos, telefono, fechaInicio, cargo);
        try {
            ge = new Gestor_Empleado(con);
            ge.altaEmpleado(nuevoEmpleado);
            JOptionPane.showMessageDialog(null, "Empleado creado");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error SQL");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error BBDD");
        }
        borrarCampos();
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultaActionPerformed
        Empleado nuevoEmpleado = null;
        String dni = jtfDNI.getText();
        try {
            ge = new Gestor_Empleado(con);
            nuevoEmpleado = ge.consultaEmpleado(dni);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error SQL");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error BBDD");
        }
        jtfDNI.setText(nuevoEmpleado.getDni());
        jtfNombre.setText(nuevoEmpleado.getNombre());
        jtfApellidos.setText(nuevoEmpleado.getApellidos());
        jtfTelefono.setText(String.valueOf(nuevoEmpleado.getTelefono()));
        jtfFechaInicio.setText(nuevoEmpleado.getFechaInicio());
        jcbCargo.setSelectedItem(nuevoEmpleado.getCargo());
    }//GEN-LAST:event_jbConsultaActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        int modificaciones;
        String dni = jtfDNI.getText();
        String nombre = jtfNombre.getText();
        String apellidos = jtfApellidos.getText();
        int telefono = Integer.parseInt(jtfTelefono.getText());
        String fechaInicio = jtfFechaInicio.getText();
        String cargo = jcbCargo.getName();
        Empleado nuevoEmpleado = new Empleado(dni, nombre, apellidos, telefono, fechaInicio, cargo);
        try {
            ge = new Gestor_Empleado(con);
            modificaciones = ge.modificarEmpleado(nuevoEmpleado);
            JOptionPane.showMessageDialog(null, "Clientes modificados" + modificaciones);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error BBDD");
        }
        borrarCampos();
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        String dni = jtfDNI.getText();
        try {
            ge = new Gestor_Empleado(con);
            ge.borrarEmpleado(dni);
            JOptionPane.showMessageDialog(null, "Empleado eliminado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error BBDD");
        }
        borrarCampos();
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jtfApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfApellidosActionPerformed

    
    
    private void borrarCampos() {
        jtfDNI.setText("");
        jtfNombre.setText("");
        jtfApellidos.setText("");
        jtfTelefono.setText("");
        jtfFechaInicio.setText("");
        jcbCargo.setName("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbConsulta;
    private javax.swing.JButton jbModificar;
    private javax.swing.JComboBox<String> jcbCargo;
    private javax.swing.JTextField jtfApellidos;
    private javax.swing.JTextField jtfDNI;
    private javax.swing.JTextField jtfFechaInicio;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables
}
